### PR TITLE
Add Slack integration + count down instead of up

### PR DESCRIPTION
**Pull request by gitviola**
- [x] Count down to 00:00 instead of up so you know how much time is still left
- [x] Add breaks (5 min and 10 min)
- [x] Show stop button only when timer is started
- [x] Add settings for Slack
- [x] Set Slack status while focus mode + set do not disturb mode if activated
- [x] Improve wording of notifications
- [x] Start break right after Pomodoro
- [x] Render error box if something doesn't work with the Slack API so the user knows

screen shot 2018-03-18 at 05 35 31

screen shot 2018-03-18 at 05 35 42

screen shot 2018-03-18 at 20 33 54

screen shot 2018-03-18 at 20 34 33

### CODE REVIEW

**Comment by veloxy** [comment]
This looks great! I am however, unable to get the slack integration working. Could you add instructions to the docs, or in the settings menu on how to get a token?

**Comment by gitviola** [comment]
@veloxy https://api.slack.com/custom-integrations/legacy-tokens this is where to get a token. Good point, I’ll add better instructions to the settings page so people know how to set it up

**Comment by veloxy** [comment]
@schurig Right, yeah that's what i was trying. I wasn't able to copy paste into the settings window so I typed it. Now I see the token was much longer than I thought 😄

The paste issue might be due to the keyup event?

**Comment by gitviola** [comment]
Yes that might be. I’ll have a look at that :) I thought it was wise to put it because maybe some people don’t leave the field after typing it in. Didn’t want to put a save button because it would be inconsistent with most apps. Also maybe I should add an error-message when API requests fail. Just so the person knows that the app couldn’t set the Slack status because of rate limit or a wrong token ect

**Comment by gitviola** [comment]
@veloxy should be fixed now. Also I now render an error-box when something with Slack didn't work so the user is aware of it.

**Comment by veloxy** [comment]
Thanks man, works great! I'll merge and make a new release!

**Pull request merged**
